filter:
    excluded_paths: [tests/*, exemplos/*, manuais/*]

build:
    nodes:
        php71:
            environment:
                php: 7.1
    dependencies:
        override:
            - composer install --no-interaction
checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_cs_fixer:
        config: { level: psr2 }