filter:
    excluded_paths: [tests/*, exemplos/*]

build:
    environment:
        php: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=tests/_reports/logs/clover.xml'
                coverage:
                    file: 'tests/_reports/logs/clover.xml'
                    format: 'clover'

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true