version: '3.7'

services:

  laravel-boleto:
    build: .
    container_name: laravel-boleto
    tty: true
    volumes:
      - .:/var/www
    networks:
      - laravel-boleto-network

networks:
  laravel-boleto-network:
    driver: bridge
